# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotclaude" do
  name "dotclaude"
  desc "Sync your Claude Code configuration across machines"
  homepage "https://github.com/daniel7an/dotclaude"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dotclaude"

  on_macos do
    on_intel do
      url "https://github.com/daniel7an/dotclaude/releases/download/v#{version}/dotclaude_#{version}_darwin_amd64.tar.gz"
      sha256 "530dd13a523b74fc1594d3c495674cb7e861fe528f541cf74be98beef4a65261"
    end
    on_arm do
      url "https://github.com/daniel7an/dotclaude/releases/download/v#{version}/dotclaude_#{version}_darwin_arm64.tar.gz"
      sha256 "18ce1344f4dda8c449dc8c9da7f011e9a7bec00a5b398c66aaf0b26b44177c63"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/daniel7an/dotclaude/releases/download/v#{version}/dotclaude_#{version}_linux_amd64.tar.gz"
      sha256 "2cc941e89e3f87f54dd753cb05a924f0f2591a6f76c9de0bc59af5015b7c3f92"
    end
    on_arm do
      url "https://github.com/daniel7an/dotclaude/releases/download/v#{version}/dotclaude_#{version}_linux_arm64.tar.gz"
      sha256 "d88c0c8dfb9dbcd9543a36988c234b9941608111e95918ced49f73a4478ccd5f"
    end
  end

  # No zap stanza required
end
